import { Metadata } from "next";
import "../styles/globals.css";

import { Space_Grotesk } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";

export const metadata: Metadata = {
  title: "batyrkhan portfolio",
  description: "Generated by create next app",
};

const spaceGrotesk = Space_Grotesk({
  weight: ["500", "700"],
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={spaceGrotesk.className}>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}

{
  /* <Head>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link
    href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@500;700&display=swap"
    rel="stylesheet"
  />
</Head>; */
}
